# Generated by Django 5.0.4 on 2024-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='car',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
    ]
