# Generated by Django 5.0.4 on 2024-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsApi', '0002_car_description_car_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='car',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
